### ISSUE TITLE
it does not support custom post type?

### ISSUE THREAD

**Issue by badpenguin** [dragonmantank/fillet-sculpin-bundle#2]
it does not support custom post type?

**Comment by dragonmantank** [comment]
I haven't tried it with a custom post type, but it should work. The only caveat I think is that all posts, regardless of type, would be converted to a Sculpin post type. 

If not, if you could send a sample XML to the main fillet project at https://github.com/dragonmantank/fillet I'll see what I can do!

**Comment by badpenguin** [comment]
never mind, the bundle does only a very simple import, its not suitable to do a complete porting of a medium-complex wordpress site;
i've writting a little "raw" importer myself
